http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /benthos
  debug_endpoints: true

redpanda:
  seed_brokers: ["crpac7e9sfrjbm1l60og.any.eu-central-1.mpx.prd.cloud.redpanda.com:9092"]
#  logs_topic: logs-ingester
  logs_level: info
  client_id: benthos
  rack_id: ""
  timeout: 10s
  max_message_bytes: 1MB
  sasl:
    - mechanism: SCRAM-SHA-256
      username: customer-1
      password: ${REDPANDA_PASSWORD}
  tls:
    enabled: true

input:
  label: "logs_ingester_kafka_input"
  kafka_franz:
    seed_brokers: ["crpac7e9sfrjbm1l60og.any.eu-central-1.mpx.prd.cloud.redpanda.com:9092"]
    topics: ["logs"]
    regexp_topics: false
    consumer_group: "foo"
    auto_replay_nacks: true
    batching:
      count: 1000
      byte_size: 0
      period: 10s
      check: ""
      processors: [ ] # No default (optional)
    sasl:
      - mechanism: SCRAM-SHA-256
        username: customer-1
        password: ${REDPANDA_PASSWORD}
    tls:
      enabled: true

pipeline:
  processors:
    - loki_processor:
        labels:
          - redpanda.*
          - pod_id
    - protobuf:
        operator: from_json
        message: logproto.PushRequest
        import_paths: [ schemas ]
    - catch:
        - mapping: |
            root = deleted()
    - compress:
        algorithm: snappy

output:
  label: "logs_ingester_http_output"
  http_client:
    url: ${LOKI_URL}
    verb: POST
    timeout: 5s
    basic_auth:
      enabled: true
      username: ${LOKI_USERNAME}
      password: ${LOKI_PASSWORD}