input:
  broker_pod_metrics:
      namespace: green
      pod: green-0
      container: redpanda
      labels:
        kubernetes_image: $.spec.containers[0].image
        kubernetes_node: $.spec.nodeName
        kubernetes_pod_id: $.metadata.uid
        kubernetes_host: $.spec.hostname
        kubernetes_pod: $.metadata.name
        kubernetes_namespace: $.metadata.namespace
        kubernetes_container: $.spec.containers[0].name

pipeline:
  processors:
    - mimir_processor: {}
    - protobuf:
        operator: from_json
        message: cortexpb.WriteRequest
        import_paths: [ schemas ]
    - catch:
        - mapping: |
            root = deleted()
    - compress:
        algorithm: snappy

output:
  http_client:
    url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    verb: POST
    timeout: 5s
    basic_auth:
      enabled: true
      username: 1796533
      password: redacted
